name: Öykü Yarışmaları
description: >
    Hikaye, öykü, mikro öykü, roman yarışmalarının listelendiği adres
about: >
    Elimden geldiğince ülkemizde düzenlenen öykü yarışmalarını toplamayı amaçlıyorum. Siz de katkıda bulabilirsiniz.

master_repo: false
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo: logo.png

rtl: false
owner:
  name: Uğur Atmaca
  email: "info@uguratmaca.com"
  twitter: uguratm
  github: https://github.com/uguratmaca
  linkedin: https://www.linkedin.com/in/atmacaugur/
  avatar: https://images.gr-assets.com/users/1438516176p6/36802906.jpg

# Analytics and webmaster tools stuff goes here
google_analytics: UA-122320408-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
